/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32f407xx.h"
#include "stm32f407_gpio.h"

void delay(void)
{
	for(uint32_t i=0; i<500000; i++);
}


int main(void)
{
	GPIO_PinConfig_t GpioLedConfig;

	GPIO_Handle_t GpioLed;

	GpioLed.pGPIOx = GPIOD;
	GpioLed.pGPIO_PinConfig = &GpioLedConfig;

	GpioLed.pGPIO_PinConfig-> GPIO_PinNumber = GPIO_PIN_NO_12;
	GpioLed.pGPIO_PinConfig-> GPIO_PinMode = GPIO_MODE_OUT;
	GpioLed.pGPIO_PinConfig-> GPIO_PinSpeed = GPIO_SPEED_FAST;
	GpioLed.pGPIO_PinConfig-> GPIO_PinPuPdControl = GPIO_NO_PUPD;
	GpioLed.pGPIO_PinConfig-> GPIO_PinOutputType = GPIO_OP_TYPE_PP;

	GPIO_Init(&GpioLed);  //GPIO_Init() already enables the clock so no nee to give that again

	while(1)
	{
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_12);
	    delay();

	}

	return 0;

}
